-- ====================== TABELAS DE USUÁRIO ======================
CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  senha_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS historico (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  pergunta TEXT NOT NULL,
  sql_gerado TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tokens_recuperacao (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  token CHAR(6) NOT NULL,
  expira_em TIMESTAMP NOT NULL,
  usado BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES usuarios(id) ON DELETE CASCADE
);



-- Materiais
CREATE TABLE IF NOT EXISTS sap_mara (
  MATNR VARCHAR(18) PRIMARY KEY,
  MATKL VARCHAR(9),
  MTART VARCHAR(4),
  MEINS VARCHAR(3),
  MAKTX VARCHAR(40),
  NTGEW DECIMAL(13,3),
  ERSDA DATE
);

-- Descrição do material
CREATE TABLE IF NOT EXISTS sap_makt (
  MATNR VARCHAR(18),
  SPRAS VARCHAR(1) DEFAULT 'P',
  MAKTX VARCHAR(40),
  PRIMARY KEY (MATNR, SPRAS)
);

-- Estoque por depósito
CREATE TABLE IF NOT EXISTS sap_mard (
  MATNR VARCHAR(18),
  WERKS VARCHAR(4),
  LGORT VARCHAR(4),
  LABST DECIMAL(13,3),
  PRIMARY KEY (MATNR, WERKS, LGORT)
);

-- Dados MRP por centro
CREATE TABLE IF NOT EXISTS sap_marc (
  MATNR VARCHAR(18),
  WERKS VARCHAR(4),
  DISPO VARCHAR(3),
  DISMM VARCHAR(2),
  MINBE DECIMAL(13,3),
  EISBE DECIMAL(13,3),
  LGPRO VARCHAR(4),
  PRIMARY KEY (MATNR, WERKS)
);

-- Movimentações de estoque
CREATE TABLE IF NOT EXISTS sap_mseg (
  MBLNR VARCHAR(10),
  ZEILE VARCHAR(4),
  BWART VARCHAR(3),
  MATNR VARCHAR(18),
  WERKS VARCHAR(4),
  LGORT VARCHAR(4),
  MENGE DECIMAL(13,3),
  DMBTR DECIMAL(13,2),
  BUDAT DATE,
  PRIMARY KEY (MBLNR, ZEILE)
);

-- Ordens de produção - Cabeçalho
CREATE TABLE IF NOT EXISTS sap_afko (
  AUFNR VARCHAR(12) PRIMARY KEY,
  MATNR VARCHAR(18),
  WERKS VARCHAR(4),
  GAMNG DECIMAL(13,3),
  GMEIN VARCHAR(3),
  GSTRI DATE,
  GETRI DATE,
  GSTRS DATE,
  GETRS DATE,
  AUFART VARCHAR(4)
);

-- Ordens de produção - Posições
CREATE TABLE IF NOT EXISTS sap_afpo (
  AUFNR VARCHAR(12),
  POSNR VARCHAR(4),
  MATNR VARCHAR(18),
  WERKS VARCHAR(4),
  PSMNG DECIMAL(13,3),
  WEMNG DECIMAL(13,3),
  LGORT VARCHAR(4),
  PRIMARY KEY (AUFNR, POSNR)
);

-- Confirmações de produção
CREATE TABLE IF NOT EXISTS sap_afru (
  AUFNR VARCHAR(12),
  VORNR VARCHAR(4),
  RUECK VARCHAR(10),
  RMZHL VARCHAR(4),
  ISMNW DECIMAL(13,3),
  GMEIN VARCHAR(3),
  ISRÜW DECIMAL(9,2),
  ISBEW DECIMAL(9,2),
  BUDAT DATE,
  PRIMARY KEY (RUECK, RMZHL)
);

-- Reservas de componentes
CREATE TABLE IF NOT EXISTS sap_resb (
  RSNUM VARCHAR(10),
  RSPOS VARCHAR(4),
  AUFNR VARCHAR(12),
  MATNR VARCHAR(18),
  WERKS VARCHAR(4),
  LGORT VARCHAR(4),
  BDMNG DECIMAL(13,3),
  ENMNG DECIMAL(13,3),
  BDTER DATE,
  PRIMARY KEY (RSNUM, RSPOS)
);

-- Ordens de venda - Cabeçalho
CREATE TABLE IF NOT EXISTS sap_vbak (
  VBELN VARCHAR(10) PRIMARY KEY,
  AUART VARCHAR(4),
  VKORG VARCHAR(4),
  VTWEG VARCHAR(2),
  SPART VARCHAR(2),
  KUNNR VARCHAR(10),
  ERDAT DATE,
  NETWR DECIMAL(15,2),
  WAERK VARCHAR(5)
);

-- Faturamento - Cabeçalho
CREATE TABLE IF NOT EXISTS sap_vbrk (
  VBELN VARCHAR(10) PRIMARY KEY,
  FKART VARCHAR(4),
  FKDAT DATE,
  KUNAG VARCHAR(10),
  NETWR DECIMAL(15,2),
  MWSBP DECIMAL(15,2),
  WAERK VARCHAR(5),
  VKORG VARCHAR(4)
);

-- Faturamento - Posições
CREATE TABLE IF NOT EXISTS sap_vbrp (
  VBELN VARCHAR(10),
  POSNR VARCHAR(6),
  MATNR VARCHAR(18),
  FKIMG DECIMAL(13,3),
  NETWR DECIMAL(15,2),
  WERKS VARCHAR(4),
  PRIMARY KEY (VBELN, POSNR)
);

-- Pedidos de compra - Cabeçalho
CREATE TABLE IF NOT EXISTS sap_ekko (
  EBELN VARCHAR(10) PRIMARY KEY,
  BSART VARCHAR(4),
  LIFNR VARCHAR(10),
  EKORG VARCHAR(4),
  BEDAT DATE,
  WAERS VARCHAR(5)
);

-- Pedidos de compra - Posições
CREATE TABLE IF NOT EXISTS sap_ekpo (
  EBELN VARCHAR(10),
  EBELP VARCHAR(5),
  MATNR VARCHAR(18),
  WERKS VARCHAR(4),
  MENGE DECIMAL(13,3),
  NETPR DECIMAL(11,2),
  WAERS VARCHAR(5),
  EINDT DATE,
  PRIMARY KEY (EBELN, EBELP)
);

-- Clientes
CREATE TABLE IF NOT EXISTS sap_kna1 (
  KUNNR VARCHAR(10) PRIMARY KEY,
  NAME1 VARCHAR(35),
  ORT01 VARCHAR(35),
  REGIO VARCHAR(3),
  LAND1 VARCHAR(3),
  STCD1 VARCHAR(16)
);

-- Fornecedores
CREATE TABLE IF NOT EXISTS sap_lfa1 (
  LIFNR VARCHAR(10) PRIMARY KEY,
  NAME1 VARCHAR(35),
  ORT01 VARCHAR(35),
  REGIO VARCHAR(3),
  LAND1 VARCHAR(3),
  STCD1 VARCHAR(16)
);

-- Ordens de manutenção
CREATE TABLE IF NOT EXISTS sap_aufk (
  AUFNR VARCHAR(12) PRIMARY KEY,
  AUART VARCHAR(4),
  WERKS VARCHAR(4),
  EQUNR VARCHAR(18),
  ERDAT DATE,
  GSTRP DATE,
  GETRP DATE,
  KOSTL VARCHAR(10)
);

-- Notificações de qualidade
CREATE TABLE IF NOT EXISTS sap_qmel (
  QMNUM VARCHAR(12) PRIMARY KEY,
  QMART VARCHAR(2),
  MATNR VARCHAR(18),
  WERKS VARCHAR(4),
  QMTXT VARCHAR(40),
  ERDAT DATE,
  STAT VARCHAR(5)
);