CREATE TABLE IF NOT EXISTS sap_mara (
  MATNR VARCHAR(18) PRIMARY KEY,
  MATKL VARCHAR(9),
  MTART VARCHAR(4),
  MEINS VARCHAR(3),
  MAKTX VARCHAR(40),
  NTGEW DECIMAL(13,3),
  ERSDA DATE
);

CREATE TABLE IF NOT EXISTS sap_mard (
  MATNR VARCHAR(18),
  WERKS VARCHAR(4),
  LGORT VARCHAR(4),
  LABST DECIMAL(13,3),
  PRIMARY KEY (MATNR, WERKS, LGORT)
);

CREATE TABLE IF NOT EXISTS sap_mseg (
  MBLNR VARCHAR(10),
  ZEILE VARCHAR(4),
  BWART VARCHAR(3),
  MATNR VARCHAR(18),
  WERKS VARCHAR(4),
  LGORT VARCHAR(4),
  MENGE DECIMAL(13,3),
  DMBTR DECIMAL(13,2),
  BUDAT DATE,
  PRIMARY KEY (MBLNR, ZEILE)
);

CREATE TABLE IF NOT EXISTS sap_afko (
  AUFNR VARCHAR(12) PRIMARY KEY,
  MATNR VARCHAR(18),
  WERKS VARCHAR(4),
  GAMNG DECIMAL(13,3),
  GMEIN VARCHAR(3),
  GSTRI DATE,
  GETRI DATE,
  GSTRS DATE,
  GETRS DATE,
  AUFART VARCHAR(4)
);

CREATE TABLE IF NOT EXISTS sap_vbrk (
  VBELN VARCHAR(10) PRIMARY KEY,
  FKART VARCHAR(4),
  FKDAT DATE,
  KUNAG VARCHAR(10),
  NETWR DECIMAL(15,2),
  MWSBP DECIMAL(15,2),
  WAERK VARCHAR(5),
  VKORG VARCHAR(4)
);

CREATE TABLE IF NOT EXISTS sap_vbrp (
  VBELN VARCHAR(10),
  POSNR VARCHAR(6),
  MATNR VARCHAR(18),
  FKIMG DECIMAL(13,3),
  NETWR DECIMAL(15,2),
  WERKS VARCHAR(4),
  PRIMARY KEY (VBELN, POSNR)
);

CREATE TABLE IF NOT EXISTS sap_ekko (
  EBELN VARCHAR(10) PRIMARY KEY,
  BSART VARCHAR(4),
  LIFNR VARCHAR(10),
  EKORG VARCHAR(4),
  BEDAT DATE,
  WAERS VARCHAR(5)
);

CREATE TABLE IF NOT EXISTS sap_ekpo (
  EBELN VARCHAR(10),
  EBELP VARCHAR(5),
  MATNR VARCHAR(18),
  WERKS VARCHAR(4),
  MENGE DECIMAL(13,3),
  NETPR DECIMAL(11,2),
  WAERS VARCHAR(5),
  EINDT DATE,
  PRIMARY KEY (EBELN, EBELP)
);

CREATE TABLE IF NOT EXISTS sap_kna1 (
  KUNNR VARCHAR(10) PRIMARY KEY,
  NAME1 VARCHAR(35),
  ORT01 VARCHAR(35),
  REGIO VARCHAR(3),
  LAND1 VARCHAR(3),
  STCD1 VARCHAR(16)
);

CREATE TABLE IF NOT EXISTS sap_lfa1 (
  LIFNR VARCHAR(10) PRIMARY KEY,
  NAME1 VARCHAR(35),
  ORT01 VARCHAR(35),
  REGIO VARCHAR(3),
  LAND1 VARCHAR(3),
  STCD1 VARCHAR(16)
);

CREATE TABLE IF NOT EXISTS sap_aufk (
  AUFNR VARCHAR(12) PRIMARY KEY,
  AUART VARCHAR(4),
  WERKS VARCHAR(4),
  EQUNR VARCHAR(18),
  ERDAT DATE,
  GSTRP DATE,
  GETRP DATE,
  KOSTL VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS sap_qmel (
  QMNUM VARCHAR(12) PRIMARY KEY,
  QMART VARCHAR(2),
  MATNR VARCHAR(18),
  WERKS VARCHAR(4),
  QMTXT VARCHAR(40),
  ERDAT DATE,
  STAT VARCHAR(5)
);